version: "3.9"

services:
  lowcodeNodered:
    build: 
      context: ./
      dockerfile: ../nodered/Dockerfile
    image: steedos/steedos-project-lowcode-nodered:latest
    container_name: steedos-project-lowcode-nodered
    ports:
      - "1880:1880"
    environment:
      - ROOT_URL=http://127.0.0.1