version: "3.9"

services:
  lowcodeNodered:
    build: 
      context: ./
      dockerfile: ../node-red/Dockerfile
    image: steedos/steedos-project-nodered:latest
    container_name: steedos-project-nodered
    ports:
      - "1880:1880"
    environment:
      - ROOT_URL=https://5000-steedos-steedosplatform-jiaahdvmfa8.ws-eu118.gitpod.io
      - STEEDOS_STORAGE_DIR=/storage